### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by GarPit** [kostya/eye-http#5]
What about authentication? Do you plan to add this or maybe have a recipe for adding this feature?

**Comment by kostya** [comment]
basic auth with nginx?

**Comment by GarPit** [comment]
Do you mean using Eye behind Nginx?

**Comment by kostya** [comment]
eye-http experimental feature.
You can try to add auth if you want with pull request. or use auth of nginx or something.

**Comment by GarPit** [comment]
Ok, good
